# Generated by Django 5.0.6 on 2024-06-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_contadordata_luminosidadedata_temperaturadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UmidadeData',
        ),
    ]
